FROM debian:8
MAINTAINER DREAM3D Community

ADD DREAM3D_Data/ /usr/src/DREAM3D_Data/

# This is to be used as a Docker Data Volume Container
# Create with
#   docker create --name dream3d-data dream3d/data
CMD /bin/true
